# Generated by Django 6.0.7 on 2026-07-28 07:30

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 28, 7, 30, 21, 545121, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='friend',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 28, 7, 30, 21, 545159, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField(max_length=500)),
                ('input', models.TextField(max_length=500)),
                ('output', models.TextField(max_length=500)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.friend')),
            ],
        ),
    ]
