# Generated by Django 6.0.7 on 2026-07-28 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_friend_create_time_alter_friend_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 28, 9, 50, 43, 398579, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='friend',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 28, 9, 50, 43, 398595, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='input',
            field=models.TextField(max_length=10000),
        ),
    ]
