# Generated by Django 6.0.7 on 2026-07-28 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_friend_create_time_alter_friend_update_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='friend',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
