# Generated by Django 6.0.7 on 2026-08-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_voice_character_voice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='voice',
        ),
    ]
